<a href="https://colab.research.google.com/github/ashwinii-17/JavaScript-Event-Handling/blob/main/DeepE2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#different tensor representations in neural networks
#Scalar (0-D Tensor)
#to print scalars
import numpy as np
x=np.array(8)
print(x)

8


In [2]:
#to print dimensions
print(x.ndim)

0


In [3]:
#Printing a Vector Using a Python List
vec = [10, 20, 30, 40, 50]
print(vec)

[10, 20, 30, 40, 50]


In [4]:
#Printing Vector Elements One by One
x= [2,3,4]
for element in x:
  print(element)

2
3
4


In [5]:
#Printing Vector with Index
x = [5, 10, 15]
for i, val in enumerate(x):
    print(f"Index {i}: {val}")

Index 0: 5
Index 1: 10
Index 2: 15


In [23]:
#Vector (1-D Tensor)
#to print vectors
x=np.array([2,3,4])
print(x)
print(x.ndim)
print(x.shape)

[2 3 4]
1
(3,)


In [7]:
#Printing Vector Elements One by One
x=np.array([2,3,4])
#for element in x:
print(x)
print(x.ndim)

[2 3 4]
1


In [8]:
#2DMatrix (2-D Tensor)
#to print vectors
import numpy as np
x=np.array([[2,3,4],[6,7,8],[10,11,12]])
print(x)
print(x.ndim)
print(x.shape)

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
2
(3, 3)


In [9]:
#3-D Tensor (Images / Time Series) - There are 2 blocks, Each block has 2 rows, Each row has 3 elements
import numpy as np

x = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])

print(x.ndim)
print(x.shape)

3
(2, 2, 3)


In [10]:
#3-D Tensor (Images / Time Series)
#to print vectors
x=np.array([[[2,3,4],[6,7,8],[10,11,12]],[[2,3,4],[6,7,8],[10,11,12]],[[2,3,4],[6,7,8],[10,11,12]],[[3,4,5],[4,5,6],[6,7,8]]])
print(x)
print(x.ndim)
print(x.shape)
#Color images → (height, width, channels), Video frames and Time-series batches

[[[ 2  3  4]
  [ 6  7  8]
  [10 11 12]]

 [[ 2  3  4]
  [ 6  7  8]
  [10 11 12]]

 [[ 2  3  4]
  [ 6  7  8]
  [10 11 12]]

 [[ 3  4  5]
  [ 4  5  6]
  [ 6  7  8]]]
3
(4, 3, 3)


In [11]:
#4-D Tensor (Batch of Images)
x = np.random.rand(10, 28, 28, 1)  #Batch size → 10 samples, 28 - Image height & width, 1- Number of channels (grayscale image)
print(x.ndim)
print(x.shape)
#Used in CNNs:10 images, 28×28 pixels, 1 channel (grayscale)

4
(10, 28, 28, 1)


In [12]:
#access and manipulate string tensors
import tensorflow as tf
# Create a string tensor
string_tensor = tf.constant(["Alliance", "University", "is great!"])

# String length
string_length = tf.strings.length(string_tensor)
print("String Lengths:", string_length.numpy())

String Lengths: [ 8 10  9]


In [13]:
#Tensor Representation Using TensorFlow
import tensorflow as tf
x = tf.constant([[1, 2, 3], [4, 5, 6]])
print(x)


tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [14]:
#Column Vector vs Row Vector
x = np.array([1,2,3])
print(x.reshape(1,3))   # Row vector
print(x.reshape(3,1))   # Column vector

[[1 2 3]]
[[1]
 [2]
 [3]]


In [15]:
#Note: A tensor is a generalization of scalars, vectors, and matrices into higher dimensions
#Tensor Type	Dimensions	Example Shape
#Scalar	       0-D	        ()
#Vector	       1-D	        (n,)
#Matrix	       2-D	        (r, c)
#3-D Tensor	   3-D	      (x, y, z)
#4-D Tensor	   4-D	    (batch, h, w, c)